using System.Security.Claims; using Cameramg.Data; using Cameramg.Models; using Cameramg.Services; using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore;
namespace Cameramg.Controllers;
[ApiController, Route("api/imagens")]
public class ImagensController(AppDbContext db, FileStorageService storage):ControllerBase
{
 [HttpGet, AllowAnonymous] public async Task<IActionResult> Listar([FromQuery]long? publicacaoId,[FromQuery]int page=1,[FromQuery]int pageSize=50){var q=db.Imagens.AsNoTracking().Where(x=>x.Visivel).AsQueryable(); if(publicacaoId.HasValue) q=q.Where(x=>x.PublicacaoId==publicacaoId); var total=await q.CountAsync(); var itens=await q.OrderByDescending(x=>x.CriadoEm).Skip((page-1)*pageSize).Take(pageSize).ToListAsync(); return Ok(new {itens,page,pageSize,total});}
 [HttpPost("upload"), Authorize(Policy="Editor")] public async Task<IActionResult> Upload([FromForm]IFormFile imagem,[FromForm]string? titulo,[FromForm]long? publicacaoId=null,[FromForm]string pasta="imagens",CancellationToken ct=default){if(imagem==null||imagem.Length==0)return BadRequest("Imagem inválida."); if(!string.IsNullOrWhiteSpace(imagem.ContentType)&&!imagem.ContentType.StartsWith("image/"))return BadRequest("O arquivo enviado não é uma imagem."); var s=await storage.SalvarAsync(imagem,pasta,ct); var i=new Imagem{UsuarioId=Uid(),PublicacaoId=publicacaoId,Titulo=string.IsNullOrWhiteSpace(titulo)?Path.GetFileNameWithoutExtension(imagem.FileName):titulo,NomeArquivo=s.nome,CaminhoRelativo=s.caminho,Origem="portal",Visivel=true}; db.Imagens.Add(i); await db.SaveChangesAsync(ct); return Ok(new { i.Id, i.UsuarioId, i.PublicacaoId, i.Titulo, i.NomeArquivo, i.CaminhoRelativo, caminho = i.CaminhoRelativo, url = i.CaminhoRelativo, arquivo = i.CaminhoRelativo, i.Origem, i.Visivel, i.CriadoEm });} 
 [HttpDelete("{id:long}"), Authorize(Policy="Editor")] public async Task<IActionResult> Remover(long id){var i=await db.Imagens.FindAsync(id)??throw new InvalidOperationException("Imagem não encontrada."); if(Uid().HasValue && i.UsuarioId!=Uid()) return Forbid(); i.Visivel=false; await db.SaveChangesAsync(); return NoContent();}
 private long? Uid()=>long.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier), out var id)?id:null;
}
